"""Opt-in PostgreSQL proof for the h10 assignment JSON hardening migration.

Set ``LEARNHOUSE_RUN_ASSIGNMENT_MIGRATION_PG_INTEGRATION=1`` and provide an
isolated, loopback-only ``LEARNHOUSE_ASSIGNMENT_MIGRATION_PG_TEST_URL``. The
test creates and removes one random schema; it never reads the configured
application database URL or runs against persistent application tables.
"""

from __future__ import annotations

import importlib.util
import ipaddress
import os
import re
from pathlib import Path
from uuid import uuid4

import pytest
from alembic.migration import MigrationContext
from alembic.operations import Operations
from sqlalchemy import text
from sqlalchemy.engine import URL, make_url
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncEngine, create_async_engine


API_ROOT = Path(__file__).resolve().parents[3]
MIGRATION_PATH = (
    API_ROOT / "migrations" / "versions" / "i0j1k2l3m4n5_harden_assignment_json_defaults.py"
)
_ENABLE_ENV = "LEARNHOUSE_RUN_ASSIGNMENT_MIGRATION_PG_INTEGRATION"
_URL_ENV = "LEARNHOUSE_ASSIGNMENT_MIGRATION_PG_TEST_URL"
_DATABASE_RE = re.compile(
    r"^learnhouse_assignment_migration_(?:test|integration)(?:_[a-z0-9]+)*$"
)
_SCHEMA_RE = re.compile(r"^assignment_json_h10_[a-f0-9]{32}$")


def _is_loopback_host(hostname: str | None) -> bool:
    if not hostname:
        return False
    if hostname.rstrip(".").lower() == "localhost":
        return True
    try:
        return ipaddress.ip_address(hostname).is_loopback
    except ValueError:
        return False


def _isolated_postgres_url() -> URL:
    if os.getenv(_ENABLE_ENV, "").lower() not in {"1", "true", "yes"}:
        pytest.skip(f"set {_ENABLE_ENV}=1 to run assignment migration integration")

    raw_url = os.getenv(_URL_ENV)
    if not raw_url:
        pytest.skip(f"set {_URL_ENV} to an isolated PostgreSQL test database")

    url = make_url(raw_url)
    if url.get_backend_name() != "postgresql":
        raise pytest.UsageError(f"{_URL_ENV} must use PostgreSQL")
    if not _is_loopback_host(url.host) or url.port is None:
        raise pytest.UsageError(f"{_URL_ENV} must target loopback with an explicit port")
    if url.query or not url.database or not _DATABASE_RE.fullmatch(url.database):
        raise pytest.UsageError(
            f"{_URL_ENV} must name an isolated learnhouse_assignment_migration_test* database"
        )
    return url.set(drivername="postgresql+asyncpg")


def _migration_module():
    spec = importlib.util.spec_from_file_location(
        "assignment_json_hardening_migration", MIGRATION_PATH
    )
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _run_migration(sync_connection, method_name: str) -> None:
    context = MigrationContext.configure(sync_connection)
    with Operations.context(context):
        getattr(_migration_module(), method_name)()


async def _apply_migration(engine: AsyncEngine, method_name: str) -> None:
    async with engine.begin() as connection:
        await connection.run_sync(_run_migration, method_name)


@pytest.fixture
async def assignment_migration_postgres() -> AsyncEngine:
    url = _isolated_postgres_url()
    schema = f"assignment_json_h10_{uuid4().hex}"
    bootstrap_engine = create_async_engine(url, pool_size=1, max_overflow=0)
    engine: AsyncEngine | None = None
    schema_created = False
    try:
        async with bootstrap_engine.begin() as connection:
            selected_database = (
                await connection.execute(text("SELECT current_database()"))
            ).scalar_one()
            if selected_database != url.database:
                pytest.fail("PostgreSQL connection did not select the supplied test database")
            await connection.execute(text(f'CREATE SCHEMA "{schema}"'))
            schema_created = True
            await connection.execute(
                text(
                    f'''CREATE TABLE "{schema}".assignment (
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        learning_objectives JSON NULL,
                        target_usergroup_ids JSON NULL
                    )'''
                )
            )

        engine = create_async_engine(
            url,
            pool_size=1,
            max_overflow=0,
            connect_args={"server_settings": {"search_path": schema}},
        )
        yield engine
    finally:
        if engine is not None:
            await engine.dispose()
        if schema_created:
            if not _SCHEMA_RE.fullmatch(schema):
                raise RuntimeError("refusing unsafe assignment migration schema cleanup")
            async with bootstrap_engine.begin() as connection:
                await connection.execute(text(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE'))
        await bootstrap_engine.dispose()


def test_assignment_migration_guard_rejects_remote_database(monkeypatch):
    monkeypatch.setenv(_ENABLE_ENV, "1")
    monkeypatch.setenv(
        _URL_ENV,
        "postgresql://test:test-only@db.invalid:5432/learnhouse_assignment_migration_test_guard",
    )

    with pytest.raises(pytest.UsageError, match="loopback"):
        _isolated_postgres_url()


async def test_assignment_json_hardening_migration_repairs_and_enforces_lists(
    assignment_migration_postgres,
):
    engine = assignment_migration_postgres
    async with engine.begin() as connection:
        await connection.execute(
            text(
                """
                INSERT INTO assignment (learning_objectives, target_usergroup_ids)
                VALUES
                    (NULL, NULL),
                    ('null'::json, 'null'::json),
                    ('[\"保留目標\"]'::json, '[42]'::json)
                """
            )
        )

    await _apply_migration(engine, "upgrade")

    async with engine.connect() as connection:
        values = (
            await connection.execute(
                text(
                    "SELECT learning_objectives::text, target_usergroup_ids::text "
                    "FROM assignment ORDER BY id"
                )
            )
        ).all()
        columns = (
            await connection.execute(
                text(
                    "SELECT column_name, is_nullable, column_default "
                    "FROM information_schema.columns "
                    "WHERE table_schema = current_schema() AND table_name = 'assignment' "
                    "AND column_name IN ('learning_objectives', 'target_usergroup_ids')"
                )
            )
        ).all()

    assert values == [("[]", "[]"), ("[]", "[]"), ('["保留目標"]', "[42]")]
    assert {name: nullable for name, nullable, _default in columns} == {
        "learning_objectives": "NO",
        "target_usergroup_ids": "NO",
    }
    assert all(default and "[]" in default and "json" in default for _, _, default in columns)

    async with engine.begin() as connection:
        inserted = (
            await connection.execute(
                text(
                    "INSERT INTO assignment DEFAULT VALUES "
                    "RETURNING learning_objectives::text, target_usergroup_ids::text"
                )
            )
        ).one()
    assert inserted == ("[]", "[]")

    async with engine.connect() as connection:
        with pytest.raises(IntegrityError):
            await connection.execute(
                text(
                    "INSERT INTO assignment (learning_objectives, target_usergroup_ids) "
                    "VALUES (NULL, '[]'::json)"
                )
            )
        await connection.rollback()

    await _apply_migration(engine, "downgrade")

    async with engine.connect() as connection:
        preserved = (
            await connection.execute(
                text(
                    "SELECT learning_objectives::text, target_usergroup_ids::text "
                    "FROM assignment WHERE id = 3"
                )
            )
        ).one()
        columns = (
            await connection.execute(
                text(
                    "SELECT column_name, is_nullable, column_default "
                    "FROM information_schema.columns "
                    "WHERE table_schema = current_schema() AND table_name = 'assignment' "
                    "AND column_name IN ('learning_objectives', 'target_usergroup_ids')"
                )
            )
        ).all()

    assert preserved == ('["保留目標"]', "[42]")
    assert {name: nullable for name, nullable, _default in columns} == {
        "learning_objectives": "YES",
        "target_usergroup_ids": "YES",
    }
    assert all(default is None for _, _, default in columns)
